### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by danrabbit** [leggettc18/leopod#3]
Hey thanks for your AppCenter submission! While reviewing you app I noticed that it doesn't contain any release tags. You'll need at least one release tag to publish your app.

You can read more about release tags here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

**Comment by leggettc18** [comment]
Thanks for filling me in! I'll get that sorted when I get off of work in a few hours. I'm guessing I'll need to update the appcenter submission pr with a new commit hash as well?

**Comment by danrabbit** [comment]
Yes, thanks!

**Comment by leggettc18** [comment]
Alright, this is resolved now by the most recent commits. Update of the appcenter-reviews json file will be pending what we decide about the sandbox exceptions.
